{
    "Swig_var_idati_set" : [
        ("repl_text" , (
            "idati = reinterpret_cast< til_t * >(argp);",
            "// idati = reinterpret_cast< til_t * >(argp);")),
    ],
    "Swig_var_idati_get" : [
        ("repl_text" , ("SWIG_as_voidptr(idati)", "SWIG_as_voidptr(/*idati*/ get_idati())")),
    ],
    "__additional_requires_idb__" : [
        "idc_parse_decl",
        "py_calc_type_size",
        "py_apply_type",
        "py_get_arg_addrs",
        "py_unpack_object_from_idb",
        "py_unpack_object_from_bv",
        "py_pack_object_to_idb",
        "py_pack_object_to_bv",
        "idc_parse_types",
        "py_idc_get_type_raw",
        "py_idc_get_local_type_raw",
        "idc_guess_type",
        "idc_get_type",
        "idc_set_local_type",
        "idc_get_local_type",
        "idc_print_type",
        "idc_get_local_type_name",
        "py_get_named_type",
        "py_get_named_type64",
        "py_print_decls",
        "py_load_til",
        "py_load_til_header",
        "py_remove_tinfo_pointer",
        "py_get_numbered_type",
    ],
}
